### PR TITLE
fix: Fix wrong model field

### PR DESCRIPTION
**Pull request by mattisonchao**
## Motivation

The Apache pulsar request model is as follows:

image

## Modifications

- Change `PartitionedIndex` to `PartitionIndex`

### CODE REVIEW

**Review by tuteng — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Review by BewareMyPower — COMMENTED** [review]
Could you explain more about it? It's very disappointing and confusing to see the ecosystem must keep the same field name with the Java client. It even makes the Java side more easily to make breaking changes. IIUC, if I changed any protected field of `MessageIdImpl`, a new breaking change would be introduced.

**Comment by mattisonchao** [comment]
@BewareMyPower 
I've changed the pic. It would be more make sense.

**Comment by mattisonchao** [comment]
In the previous design, pulsar-admin-go choose to use `messageId` as a restful request model and param. therefore, it should keep the same field as the admin server. not for pulsar clients. :)

**Comment by BewareMyPower** [comment]
Okay, I just found the REST request.

https://github.com/apache/pulsar/blob/64cd7535996c6da07bedd7d06b1c1d1477c23287/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java#L1609

**Review by BewareMyPower — APPROVED** [review]

**Comment by mattisonchao** [comment]
@tuteng  could you please cherry-pick it to previous branches by any chance?

**Pull request merged**
